[package]
name = "parser-combinator"
version = "0.1.0"
edition = "2021"


[lib]
name = "parser_combinator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"